### ISSUE TITLE
User session management

### ISSUE THREAD

**Issue by kayoumido** [kayoumido/HEIGVD-PRO-A-11#134]
globalize user management on the entire application 

## User Story 

As a user
I want to be logged in only when I need on the application
So that my application usage is enjoyable

## Task list

- [x] logout option
- [x] only see current accessible link (logged set, and unlogged set)
- [x] automatic redirection if route is still accessed in incorrect state
- [x] bearer token validity is checked on create of app.vue
- [x] adapt authentication and account creation vues to new paradigm
